### ISSUE TITLE
F * x does not work on iterator argument from each_slice

### ISSUE THREAD

**Issue by razetime** [cyoce/J-uby#3]
`p :to_a*([1,2,3,4].each_slice(2))` prints `#<Proc:0x00005560031ca788@/opt/j-uby/func.rb:103 (lambda)>`

however, 

`p [1,2,3,4].each_slice(2).map(&:to_a)` prints `[[1, 2], [3, 4]]`.

I think the behaviour should be the same since map is being used in both places.

**Comment by razetime** [comment]
`(:map+:to_a).` seems to work in the place of `:to_a*`

**Comment by cyoce** [comment]
Should be working now.
